# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class GeneApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def gene_get(self, id, **kwargs):  # noqa: E501
        """  # noqa: E501

        Get gene by id but also filter variants out by CADD and freq  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.gene_get(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: Gene ENSEMBL id (required)
        :param float gnomad_freq: gnomad allele freq threshold
        :param float cadd: CADD threshold
        :return: list[Gene]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.gene_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.gene_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def gene_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """  # noqa: E501

        Get gene by id but also filter variants out by CADD and freq  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.gene_get_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: Gene ENSEMBL id (required)
        :param float gnomad_freq: gnomad allele freq threshold
        :param float cadd: CADD threshold
        :return: list[Gene]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'gnomad_freq', 'cadd']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gene_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `gene_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'gnomad_freq' in params:
            query_params.append(('gnomad_freq', params['gnomad_freq']))  # noqa: E501
        if 'cadd' in params:
            query_params.append(('cadd', params['cadd']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['phenopolis_auth']  # noqa: E501

        return self.api_client.call_api(
            '/gene', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Gene]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
