# coding: utf-8

# flake8: noqa
"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.gene import Gene
from swagger_client.models.hpo import HPO
from swagger_client.models.patient import Patient
from swagger_client.models.simple_variant import SimpleVariant
from swagger_client.models.variant import Variant
from swagger_client.models.variant_carriers import VariantCarriers
