# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VariantCarriers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'heterozygous': 'list[str]',
        'homozygous': 'list[str]'
    }

    attribute_map = {
        'heterozygous': 'heterozygous',
        'homozygous': 'homozygous'
    }

    def __init__(self, heterozygous=None, homozygous=None):  # noqa: E501
        """VariantCarriers - a model defined in Swagger"""  # noqa: E501

        self._heterozygous = None
        self._homozygous = None
        self.discriminator = None

        if heterozygous is not None:
            self.heterozygous = heterozygous
        if homozygous is not None:
            self.homozygous = homozygous

    @property
    def heterozygous(self):
        """Gets the heterozygous of this VariantCarriers.  # noqa: E501


        :return: The heterozygous of this VariantCarriers.  # noqa: E501
        :rtype: list[str]
        """
        return self._heterozygous

    @heterozygous.setter
    def heterozygous(self, heterozygous):
        """Sets the heterozygous of this VariantCarriers.


        :param heterozygous: The heterozygous of this VariantCarriers.  # noqa: E501
        :type: list[str]
        """

        self._heterozygous = heterozygous

    @property
    def homozygous(self):
        """Gets the homozygous of this VariantCarriers.  # noqa: E501


        :return: The homozygous of this VariantCarriers.  # noqa: E501
        :rtype: list[str]
        """
        return self._homozygous

    @homozygous.setter
    def homozygous(self, homozygous):
        """Sets the homozygous of this VariantCarriers.


        :param homozygous: The homozygous of this VariantCarriers.  # noqa: E501
        :type: list[str]
        """

        self._homozygous = homozygous

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariantCarriers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
