# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gene_api import GeneApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGeneApi(unittest.TestCase):
    """GeneApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.gene_api.GeneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gene_get(self):
        """Test case for gene_get

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
