# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.phenotype_api import PhenotypeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPhenotypeApi(unittest.TestCase):
    """PhenotypeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.phenotype_api.PhenotypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hpo_get(self):
        """Test case for hpo_get

        Returns Human Phenotype Ontology (HPO)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
