# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.variant_api import VariantApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVariantApi(unittest.TestCase):
    """VariantApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.variant_api.VariantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_variants_by_id(self):
        """Test case for find_variants_by_id

        Finds Variants by id  # noqa: E501
        """
        pass

    def test_get_variant_by_id(self):
        """Test case for get_variant_by_id

        Find variant by ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
