# coding: utf-8

"""
    Phenopolis API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@phenopolis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.variant import Variant  # noqa: E501
from swagger_client.rest import ApiException


class TestVariant(unittest.TestCase):
    """Variant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariant(self):
        """Test Variant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.variant.Variant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
